-- Catalog of neural networks for staged Replicate / provider integration.
-- Safe to re-run: upserts by slug.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS neural_networks (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name               TEXT NOT NULL,
  slug               TEXT NOT NULL UNIQUE,
  category           TEXT NOT NULL CHECK (category IN ('llm', 'image', 'video', 'audio', 'editor')),
  api_available      BOOLEAN NOT NULL DEFAULT FALSE,
  api_provider       TEXT NOT NULL DEFAULT 'pending',
  input_modalities   TEXT[] NOT NULL DEFAULT '{}',
  output_modalities  TEXT[] NOT NULL DEFAULT '{}',
  status             TEXT NOT NULL DEFAULT 'catalog'
                       CHECK (status IN ('catalog', 'integrating', 'live', 'blocked')),
  replicate_model    TEXT NULL,
  notes              TEXT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS neural_networks_category_idx ON neural_networks (category);
CREATE INDEX IF NOT EXISTS neural_networks_status_idx ON neural_networks (status);

INSERT INTO neural_networks
  (name, slug, category, api_available, api_provider, input_modalities, output_modalities, status, replicate_model, notes)
VALUES
  ('ChatGPT', 'chatgpt', 'llm', TRUE, 'openai / pending', ARRAY['text','image','audio'], ARRAY['text','image','audio'], 'catalog', NULL, NULL),
  ('GPT-5.4', 'gpt-5-4', 'llm', TRUE, 'replicate', ARRAY['text','image'], ARRAY['text'], 'live', 'openai/gpt-5.4', 'assistant via /api/generate; text/image → text'),
  ('GPT-5.6 Sol', 'gpt-5-6-sol', 'llm', TRUE, 'replicate', ARRAY['text','image'], ARRAY['text'], 'live', 'openai/gpt-5.6-sol', 'generative via /api/generate; 50% off until Sept 18'),
  ('Claude Sonnet 5', 'claude', 'llm', TRUE, 'replicate', ARRAY['text'], ARRAY['text'], 'live', 'anthropic/claude-sonnet-5', 'Replicate wait API; input prompt → text'),
  ('Claude Haiku 4.5', 'claude-4-5-haiku', 'llm', TRUE, 'replicate', ARRAY['text'], ARRAY['text'], 'live', 'anthropic/claude-4.5-haiku', 'assistant via /api/generate; fast Claude 4'),
  ('Claude Opus 4.7', 'claude-opus-4-7', 'llm', TRUE, 'replicate', ARRAY['text','image'], ARRAY['text'], 'live', 'anthropic/claude-opus-4.7', 'Replicate wait; prompt + optional image → text'),
  ('Gemini 3.5 Flash', 'gemini', 'llm', TRUE, 'replicate', ARRAY['text'], ARRAY['text'], 'live', 'google/gemini-3.5-flash', 'via /api/generate; Replicate stream/wait'),
  ('Gemini 3.1 Pro', 'gemini-3-1-pro', 'llm', TRUE, 'replicate', ARRAY['text','image'], ARRAY['text'], 'live', 'google/gemini-3.1-pro', 'via /api/generate; thinking_level medium; text+image→text'),
  ('Grok', 'grok', 'llm', TRUE, 'xai / pending', ARRAY['text','image'], ARRAY['text'], 'catalog', NULL, NULL),
  ('DeepSeek V3.1', 'deepseek-v3-1', 'llm', TRUE, 'replicate', ARRAY['text'], ARRAY['text'], 'live', 'deepseek-ai/deepseek-v3.1', 'assistant via /api/generate; hybrid thinking; $0.672/1M in · $2.016/1M out'),
  ('DeepSeek V3', 'deepseek-v3', 'llm', TRUE, 'replicate', ARRAY['text'], ARRAY['text'], 'live', 'deepseek-ai/deepseek-v3', 'assistant via /api/generate'),
  ('Perplexity', 'perplexity', 'llm', TRUE, 'perplexity / pending', ARRAY['text','image'], ARRAY['text'], 'catalog', NULL, NULL),
  ('Qwen', 'qwen', 'llm', TRUE, 'alibaba / pending', ARRAY['text','image'], ARRAY['text'], 'catalog', NULL, NULL),
  ('Zhipu AI', 'zhipu-ai', 'llm', TRUE, 'zhipu / pending', ARRAY['text','image','video'], ARRAY['text','image','video'], 'catalog', NULL, NULL),
  ('MiniMax 3.0', 'minimax-3-0', 'llm', TRUE, 'replicate / pending', ARRAY['text'], ARRAY['text'], 'catalog', NULL, NULL),
  ('Ideogram', 'ideogram', 'image', TRUE, 'replicate / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Ideogram v3 Turbo', 'ideogram-v3-turbo', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'ideogram-ai/ideogram-v3-turbo', 'via /api/generate; t2i + optional style ref; $0.03/img'),
  ('Gen-4 Image', 'gen4-image', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'runwayml/gen4-image', 't2i via /api/generate; optional reference images (@ref)'),
  ('Z-Image Turbo', 'z-image-turbo', 'image', TRUE, 'replicate', ARRAY['text'], ARRAY['image'], 'live', 'prunaai/z-image-turbo', 'fast t2i via /api/generate; photoreal + text rendering'),
  ('HiDream L1 Fast', 'hidream-l1-fast', 'image', TRUE, 'replicate', ARRAY['text'], ARRAY['image'], 'live', 'prunaai/hidream-l1-fast', 'fast t2i via /api/generate'),
  ('Nano Banana Pro', 'nano-banana-pro', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'google/nano-banana-pro', 'generative via /api/generate; t2i + edit'),
  ('Nano Banana 2', 'nano-banana-2', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'google/nano-banana-2', 'via /api/generate; t2i/edit + multi-ref; $0.067–0.151/img; 1K/2K/4K'),
  ('Nano Banana 2 Lite', 'nano-banana-2-lite', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'google/nano-banana-2-lite', 'generative via /api/generate; cheapest/fastest'),
  ('GPT Image 2', 'gpt-image-2', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'openai/gpt-image-2', 'via /api/generate; text/edit; low $0.012 · medium $0.047 · high $0.128'),
  ('GPT Image 2.5 Flare', 'gpt-image-2-5-flare', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'openai/gpt-image-2.5-flare', 'via /api/generate; text/edit; low $0.012 · medium $0.047 · high $0.128 · xhigh $0.25 · max $0.50'),
  ('GPT Image 2.5 Sunburst', 'gpt-image-2-5-sunburst', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'openai/gpt-image-2.5-sunburst', 'via /api/generate; text/edit; low $0.012 · medium $0.047 · high $0.128 · xhigh $0.25 · max $0.50'),
  ('Flux', 'flux', 'image', TRUE, 'replicate / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Flux 2 Pro', 'flux-2-pro', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'black-forest-labs/flux-2-pro', 't2i + edit via /api/generate; up to 8 reference images'),
  ('Flux 1.1 Pro', 'flux-1-1-pro', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'black-forest-labs/flux-1.1-pro', 't2i via /api/generate; optional image_prompt (Redux)'),
  ('Flux Kontext Pro', 'flux-kontext-pro', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'black-forest-labs/flux-kontext-pro', 'text-based image edit via /api/generate; image required'),
  ('Seedream', 'seedream', 'image', TRUE, 'replicate / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Seedream 5.0 Pro', 'seedream-5-pro', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'bytedance/seedream-5-pro', 'via /api/generate; text/refs→image; 1K $0.045 · 2K $0.09'),
  ('Seedream 5.0 Lite Edit', 'seedream-5-lite-edit-fal', 'image', TRUE, 'fal', ARRAY['image','text'], ARRAY['image'], 'live', NULL, 'fal: fal-ai/bytedance/seedream/v5/lite/edit; image + prompt'),
  ('Seedream 5.0 Lite T2I', 'seedream-5-lite-t2i-fal', 'image', TRUE, 'fal', ARRAY['text'], ARRAY['image'], 'live', NULL, 'fal: fal-ai/bytedance/seedream/v5/lite/text-to-image; t2i'),
  ('Seedream 5.0 Pro T2I', 'seedream-5-pro-t2i-fal', 'image', TRUE, 'fal', ARRAY['text'], ARRAY['image'], 'live', NULL, 'fal: bytedance/seedream/v5/pro/text-to-image; covered by replicate seedream-5-pro'),
  ('Seedream 5.0 Pro Edit', 'seedream-5-pro-edit-fal', 'image', TRUE, 'fal', ARRAY['image','text'], ARRAY['image'], 'live', NULL, 'fal: bytedance/seedream/v5/pro/edit; covered by replicate seedream-5-pro'),
  ('Sora (GPT) Image', 'sora-gpt-image', 'image', TRUE, 'openai / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Runway Frames', 'runway-frames', 'image', TRUE, 'runway / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Grok Imagine', 'grok-imagine', 'image', TRUE, 'xai / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Grok Imagine Image 2', 'grok-imagine-image-2', 'image', TRUE, 'replicate', ARRAY['text','image'], ARRAY['image'], 'live', 'xai/grok-imagine-image-2', 't2i + edit via /api/generate'),
  ('Luma (image)', 'luma-image', 'image', TRUE, 'luma / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Higgsfield Soul', 'higgsfield-soul', 'image', TRUE, 'higgsfield / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Wan', 'wan', 'image', TRUE, 'replicate / pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Wan 3.0', 'wan-3-0', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'alibaba/wan-3', 'via /api/generate; 480p/720p/1080p up to 30s; text/image→video'),
  ('Wan 3.0 T2V', 'wan-3-0-t2v-fal', 'video', TRUE, 'fal', ARRAY['text'], ARRAY['video'], 'live', NULL, 'fal: alibaba/wan-3.0/text-to-video; t2v + audio'),
  ('Wan 3.0 I2V', 'wan-3-0-i2v-fal', 'video', TRUE, 'fal', ARRAY['image','text'], ARRAY['video'], 'live', NULL, 'fal: alibaba/wan-3.0/image-to-video; image required'),
  ('LTX 2.3 T2V', 'ltx-2-3-t2v-fal', 'video', TRUE, 'fal', ARRAY['text'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/ltx-2.3/text-to-video; t2v + audio'),
  ('LTX 2.3 T2V Fast', 'ltx-2-3-t2v-fast-fal', 'video', TRUE, 'fal', ARRAY['text'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/ltx-2.3/text-to-video/fast; t2v + audio'),
  ('LTX 2.3 I2V', 'ltx-2-3-i2v-fal', 'video', TRUE, 'fal', ARRAY['image','text'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/ltx-2.3/image-to-video; image + prompt'),
  ('LTX 2.3 I2V Fast', 'ltx-2-3-i2v-fast-fal', 'video', TRUE, 'fal', ARRAY['image','text'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/ltx-2.3/image-to-video/fast; image + prompt'),
  ('LTX 2.3 A2V', 'ltx-2-3-a2v-fal', 'video', TRUE, 'fal', ARRAY['audio','text','image'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/ltx-2.3/audio-to-video; audio required'),
  ('PixVerse V6', 'pixverse-v6', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'pixverse/pixverse-v6', 'via /api/generate; t2v/i2v + optional audio; 360p–1080p; up to 15s'),
  ('P-Video', 'p-video', 'video', TRUE, 'replicate', ARRAY['text','image','audio'], ARRAY['video'], 'live', 'prunaai/p-video', 'via /api/generate; t2v/i2v/a2v + draft; $0.005–0.04/s; up to 20s'),
  ('PixVerse V6 T2V', 'pixverse-v6-t2v-fal', 'video', TRUE, 'fal', ARRAY['text'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/pixverse/v6/text-to-video; t2v + optional audio'),
  ('PixVerse V6 I2V', 'pixverse-v6-i2v-fal', 'video', TRUE, 'fal', ARRAY['image','text'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/pixverse/v6/image-to-video; image + prompt'),
  ('MJ', 'mj', 'image', FALSE, 'pending', ARRAY['text','image'], ARRAY['image'], 'catalog', NULL, 'No official public Midjourney API'),
  ('Google Veo', 'google-veo', 'video', TRUE, 'google / pending', ARRAY['text','image','video'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Veo 3.1', 'veo-3-1', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'google/veo-3.1', 'via /api/generate; t2v/i2v + native audio; $0.20/s without · $0.40/s with'),
  ('Veo 3.1 Fast', 'veo-3-1-fast', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'google/veo-3.1-fast', 'via /api/generate; быстрый t2v/i2v + native audio; $0.10/s without · $0.15/s with'),
  ('Veo 3.1 Lite', 'veo-3-1-lite', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'google/veo-3.1-lite', 'generative via /api/generate; t2v/i2v + native audio'),
  ('Seedance 2.5', 'seedance-2-5', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'bytedance/seedance-2.5', 'via /api/generate; text/image→video + synced audio; 480p/720p up to 30s'),
  ('Seedance 2.5 HF', 'seedance-2-5-hf', 'video', TRUE, 'higgsfield', ARRAY['text','image'], ARRAY['video'], 'live', NULL, 'hf: bytedance/seedance-2.5/text-to-video|image-to-video'),
  ('Seedance 2.0', 'seedance-2-0', 'video', TRUE, 'replicate', ARRAY['text'], ARRAY['video'], 'live', 'bytedance/seedance-2.0', 'via /api/generate'),
  ('Seedance 2.0 T2V', 'seedance-2-0-t2v-fal', 'video', TRUE, 'fal', ARRAY['text'], ARRAY['video'], 'live', NULL, 'fal: bytedance/seedance-2.0/text-to-video; t2v + native audio'),
  ('Kling 2.5 Turbo Pro', 'kling-v2-5-turbo-pro', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'kwaivgi/kling-v2.5-turbo-pro', 'via /api/generate; t2v/i2v; $0.07/s; 5/10s'),
  ('Kling 2.5 Turbo Pro HF', 'kling-v2-5-turbo-pro-hf', 'video', TRUE, 'higgsfield', ARRAY['text','image'], ARRAY['video'], 'live', NULL, 'hf: kling-video/v2.5-turbo/pro/text-to-video|image-to-video'),
  ('Kling 3.0', 'kling-v3-0-hf', 'video', TRUE, 'higgsfield', ARRAY['text','image'], ARRAY['video'], 'live', NULL, 'hf: kling-video/v3.0/pro/text-to-video|image-to-video'),
  ('Veo 3.1 HF', 'veo-3-1-hf', 'video', TRUE, 'higgsfield', ARRAY['text','image'], ARRAY['video'], 'live', NULL, 'hf: veo3.1/text-to-video|image-to-video (may be model_disabled upstream)'),
  ('Kling O3 Standard I2V', 'kling-o3-standard-i2v-fal', 'video', TRUE, 'fal', ARRAY['image','text'], ARRAY['video'], 'live', NULL, 'fal: fal-ai/kling-video/o3/standard/image-to-video; image required'),
  ('MiniMax H3 Ref→Video', 'minimax-h3-ref-to-video-fal', 'video', TRUE, 'fal', ARRAY['text','image'], ARRAY['video'], 'live', NULL, 'fal: minimax/h3/reference-to-video; optional ref images'),
  ('Runway', 'runway', 'video', TRUE, 'runway / pending', ARRAY['text','image','video'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Runway Gen-4.5', 'runway-gen-4-5', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'runwayml/gen-4.5', 'generative via /api/generate; t2v/i2v'),
  ('Gen-4 Turbo', 'gen4-turbo', 'video', TRUE, 'replicate', ARRAY['image','text'], ARRAY['video'], 'live', 'runwayml/gen4-turbo', 'via /api/generate; i2v image required; $0.05/s; 5/10s 720p'),
  ('Sora', 'sora', 'video', TRUE, 'openai / pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Sora 2', 'sora-2', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'openai/sora-2', 'generative via /api/generate; discontinued after 2026-09-24'),
  ('Sora 2 Pro', 'sora-2-pro', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'blocked', 'openai/sora-2-pro', 'removed: OpenAI discontinues after 2026-09-24'),
  ('Luma', 'luma', 'video', TRUE, 'luma / pending', ARRAY['text','image','video'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Hailuo Minimax', 'hailuo-minimax', 'video', TRUE, 'replicate / pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Hailuo 02', 'hailuo-02', 'video', TRUE, 'replicate', ARRAY['text','image'], ARRAY['video'], 'live', 'minimax/hailuo-02', 'via /api/generate; t2v/i2v; $0.10–0.48/vid; 512p–1080p; 6/10s'),
  ('Hailuo 2.3 Fast', 'hailuo-2-3-fast', 'video', TRUE, 'replicate', ARRAY['image','text'], ARRAY['video'], 'live', 'minimax/hailuo-2.3-fast', 'generative i2v via /api/generate; image required'),
  ('DreamActor M2.0', 'dreamactor-m2', 'video', TRUE, 'replicate', ARRAY['image','video'], ARRAY['video'], 'live', 'bytedance/dreamactor-m2.0', 'image + driving video via /api/generate'),
  ('Higgsfield', 'higgsfield', 'video', TRUE, 'higgsfield / pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Wan Video', 'wan-video', 'video', TRUE, 'replicate / pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, NULL),
  ('FLUX 3 Video', 'flux-3-video', 'video', TRUE, 'replicate / pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, NULL),
  ('MJ Video', 'mj-video', 'video', FALSE, 'pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, 'No official public Midjourney API'),
  ('HappyHorse', 'happyhorse', 'video', TRUE, 'pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Happy Horse 1.1 T2V', 'happy-horse-1-1-t2v-fal', 'video', TRUE, 'fal', ARRAY['text'], ARRAY['video'], 'live', NULL, 'fal: alibaba/happy-horse/v1.1/text-to-video; t2v + native audio'),
  ('Gemini Omni Flash', 'gemini-omni-flash-fal', 'video', TRUE, 'fal', ARRAY['text'], ARRAY['video'], 'live', NULL, 'fal: google/gemini-omni-flash; t2v + synced audio'),
  ('Beeble', 'beeble', 'video', TRUE, 'pending', ARRAY['text','image','video'], ARRAY['video'], 'catalog', NULL, NULL),
  ('HeyGen', 'heygen', 'video', TRUE, 'heygen / pending', ARRAY['text','image','audio','video'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Grok Imagine (video)', 'grok-imagine-video', 'video', TRUE, 'xai / pending', ARRAY['text','image'], ARRAY['video'], 'catalog', NULL, NULL),
  ('Grok Imagine Video 1.5', 'grok-imagine-video-1-5', 'video', TRUE, 'replicate', ARRAY['image','text'], ARRAY['video'], 'live', 'xai/grok-imagine-video-1.5', 'via /api/generate; image→video + synced audio; 480p/720p up to 15s'),
  ('Grok Imagine Video 1.5 I2V', 'grok-imagine-video-1-5-i2v-fal', 'video', TRUE, 'fal', ARRAY['image','text'], ARRAY['video'], 'live', NULL, 'fal: xai/grok-imagine-video/v1.5/image-to-video; covered by replicate grok-imagine-video-1-5'),
  ('Elevenlabs', 'elevenlabs', 'audio', TRUE, 'elevenlabs / pending', ARRAY['text','audio'], ARRAY['audio'], 'catalog', NULL, NULL),
  ('ElevenLabs v3', 'elevenlabs-v3', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'elevenlabs/v3', 'TTS via /api/generate; text→speech'),
  ('ElevenLabs Music', 'elevenlabs-music', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'elevenlabs/music', 'via /api/generate; text→music; $0.0083/s; vocals/instrumental'),
  ('Stable Audio 2.5', 'stable-audio-2-5', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'stability-ai/stable-audio-2.5', 'via /api/generate; text→music/SFX; $0.20/file; up to 190s'),
  ('Lyria 2', 'lyria-2', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'google/lyria-2', 'text→music via /api/generate; ~30s 48kHz stereo'),
  ('MiniMax Music-01', 'minimax-music-01', 'audio', TRUE, 'replicate', ARRAY['text','audio'], ARRAY['audio'], 'live', 'minimax/music-01', 'lyrics + reference song via /api/generate; up to ~60s'),
  ('ACE-Step', 'ace-step', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'lucataco/ace-step', 'via /api/generate; tags→music; ~$0.022/run; ~60s instrumental'),
  ('Flux Music', 'flux-music', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'zsxkib/flux-music', 'text→music via /api/generate; ~10s'),
  ('MiniMax Music 2.5', 'minimax-music-2-5', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'minimax/music-2.5', 'lyrics→full song via /api/generate; up to ~5min'),
  ('ElevenLabs Scribe v2', 'elevenlabs-scribe-v2', 'audio', TRUE, 'replicate', ARRAY['audio'], ARRAY['text'], 'live', 'elevenlabs/scribe-v2', 'STT via /api/generate; audio required'),
  ('Gemini 3.1 Flash TTS', 'gemini-3-1-flash-tts', 'audio', TRUE, 'replicate', ARRAY['text'], ARRAY['audio'], 'live', 'google/gemini-3.1-flash-tts', 'via /api/generate; text→speech'),
  ('Suno', 'suno', 'audio', TRUE, 'suno / pending', ARRAY['text','audio'], ARRAY['music','audio'], 'catalog', NULL, NULL),
  ('Редактор Nano Banana Pro', 'editor-nano-banana-pro', 'editor', TRUE, 'pending', ARRAY['image','text'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Banana 2', 'banana-2', 'editor', TRUE, 'pending', ARRAY['image','text'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Clarity', 'clarity', 'editor', TRUE, 'pending', ARRAY['image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('Редактор MJ', 'editor-mj', 'editor', FALSE, 'pending', ARRAY['image','text'], ARRAY['image'], 'catalog', NULL, 'No official public Midjourney API'),
  ('Magnific', 'magnific', 'editor', TRUE, 'pending', ARRAY['image'], ARRAY['image'], 'catalog', NULL, NULL),
  ('PASD Magnify', 'pasd-magnify', 'image', TRUE, 'replicate', ARRAY['image','text'], ARRAY['image'], 'live', 'lucataco/pasd-magnify', 'upscale via /api/generate; image required; academic/non-commercial only'),
  ('Topaz AI', 'topaz-ai', 'editor', TRUE, 'topaz / pending', ARRAY['image','video'], ARRAY['image','video'], 'catalog', NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  api_available = EXCLUDED.api_available,
  api_provider = EXCLUDED.api_provider,
  input_modalities = EXCLUDED.input_modalities,
  output_modalities = EXCLUDED.output_modalities,
  status = EXCLUDED.status,
  replicate_model = EXCLUDED.replicate_model,
  notes = EXCLUDED.notes,
  updated_at = now();
